---
- name: Install  Kibana packages
  hosts: 192.168.64.64
  become: true
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_user: ubuntu
    main_ip: "{{ main_ip }}
  roles:
   - /Users/sahana.intern/ansible-ek/kib
   
   
      

