---
- name: Install Elasticsearch and Kibana packages
  hosts: 192.168.64.64
  become: true
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_user: ubuntu
    main_ip: 192.168.64.64
  roles:
   - /Users/sahana.intern/ansible-ek/elastic
   - /Users/sahana.intern/ansible-ek/kib
   

- name: Install  Metricbeat  packages
  hosts: 192.168.64.65
  become: true
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_user: ubuntu  
    main_ip: 192.168.64.64
  roles:
   - /Users/sahana.intern/ansible-ek/metric
   
- name: Install  FILEBEAT
  hosts: 192.168.64.66
  become: true
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_user: ubuntu
    main_ip: 192.168.64.64
  roles:
   - /Users/sahana.intern/ansible-ek/filebeat   
   
   


