---
# tasks file for filebeat

- name: Install Nginx
  package:
    name: nginx
    state: present

- name: Start Nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Add Elasticsearch GPG key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"

- name: Install a .deb package from the internet
  ansible.builtin.apt:
    deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.10.2-arm64.deb

- name: Set permissions for Filebeat  directory
  ansible.builtin.file:
    path: "/etc/filebeat"
    owner: ubuntu
    group: ubuntu
    mode: "0755"
    recurse: yes

- name: Configure Filebeat yml file
  template:
    src: filebeat.yml.j2
    dest: "{{ filebeat_config_path }}"
  notify: Restart Filebeat

- name: Set permissions for Filebeat configuration file
  ansible.builtin.file:
    path: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: "0644"
  become: yes

- name: Start Filebeat service
  ansible.builtin.systemd:
    name: filebeat
    state: started
    enabled: yes

